#!/bin/bash
#######################################################################
# Copyright    2015 Cortex Media
# Author    Mathieu Rhéaume <mrheaume@cortex.bz>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################################################
# This config files contains the list of containers that
# BuildDockerImagesAndPushToRepos and PullFromRepository will use
# It keeps references between the docker repos and your own app
# configuration.
#######################################################################
# Docker specific settings.
#######################################################################
REPOSITORY_URL="mydocker.repository.ca:8080"

#######################################################################
# Server specific settings.
#######################################################################
APP_DIRECTORY="/home/ubuntu/sample_app_directory"
DOCKER_COMPOSE_FILE="docker-compose-production.yml"
SERVER_IP="99.999.99.99"
# User to RSync with
SERVER_USER="ubuntu"
# User that runs docker-compose & containers
DOCKER_USER="ubuntu"

#######################################################################
# Docker specific settings.
# Structure of config line is
# "LocalImageName;DockerFilePath;DockerImageName"
#######################################################################
ARRAY_DELIMITER=";"
declare -a IMAGES_TO_BUILD
IMAGES_TO_BUILD[0]="mrheaume/sample_project_web;.;sample_project_web"
IMAGES_TO_BUILD[1]="mrheaume/sample_project_db;DockerPostgres/;sample_project_db"
IMAGES_TO_BUILD[2]="mrheaume/sample_project_nginx;DockerNginx/;sample_project_nginx"

